# ==============================================================================
# CONFIGURACIÓN DE KITTY (Hyprland / Arch Linux)
# ==============================================================================

# --- FUENTES Y LIGADURAS ---
font_family      family="Hack Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0
disable_ligatures never

# --- MÁRGENES Y APARIENCIA DE LA VENTANA ---
window_padding_width 20
background_opacity   0.98
enable_audio_bell    no
confirm_os_window_close 0

# --- CURSOR Y MOUSE ---
cursor_shape          beam
cursor_beam_thickness 1.8
cursor_blink_interval 0
mouse_hide_wait       2.0
detect_urls           yes
url_color             #61afef
url_style             curly

# --- BARRA DE PESTAÑAS (TAB BAR) ---
tab_bar_style           powerline
tab_powerline_style     angled
active_tab_foreground   #000000
active_tab_background   #98c379
inactive_tab_foreground #000000
inactive_tab_background #e06c75
tab_bar_margin_color    black

# --- INTEGRACIÓN Y ATAJOS DE TECLADO ---
shell .

# Navegación entre ventanas dentro de Kitty
map ctrl+left  neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up    neighboring_window up
map ctrl+down  neighboring_window down

# Portapapeles
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# --- INCLUSIÓN DEL TEMA DE COLOR ---
include color.ini
